<div><img style="float: right; width: 120px; vertical-align:middle" src="https://www.upm.es/sfs/Rectorado/Gabinete%20del%20Rector/Logos/EU_Informatica/ETSI%20SIST_INFORM_COLOR.png" alt="ETSISI logo" />

# Clasificación alternativa<a id="top"></a>

<i><small>Última actualización: 2023-04-21</small></i></div>
***

## Enunciado

Entrenar una red neuronal para clasificar una versión modificada del conjunto de datos MNIST con cuatro clases:

- Dígitos palo (1 y 7)
- Dígitos retorcidos (0, 6, 8 y 9)
- Dígitos sueltos (2 y 5)
- Otros dígitos (3 y 4)

Entrena la red neuronal utilizando el conjunto de entrenamiento y evalúa el rendimiento del modelo en el conjunto de _test_ mostrando la matriz de confusión. Describe de la precisión del modelo, analiza la matriz de confusión para identificar patrones o sesgos en la clasificación y por último, sugiere algunas posibles mejoras del modelo o del conjunto de datos para mejorar la precisión de la clasificación.

***

In [17]:
import numpy as np
import pandas as pd

In [16]:
df = pd.DataFrame([[1525, 0, 1, 0], [4, 2525, 5, 6], [1, 0, 1999, 1], [0, 9, 9, 2800]])
df.style.background_gradient(cmap='cool_r', axis=None)

In [23]:
y_train = np.random.randint(0, 9, 10)
y_train

array([5, 4, 7, 7, 4, 8, 3, 3, 5, 5])

In [28]:
new_y_train = np.zeros((len(y_train), 4))
new_y_train

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
for old, new in zip(y_train, new_y_train):
    if old in (1, 7):
        new[0] = 1
    elif old in (0, 6, 8, 9):
        new[1] = 1
    elif old in (2, 5):
        new[2] = 1
    else:
        new[3] = 1
new_y_train

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

***

<div><img style="float: right; width: 120px; vertical-align:top" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png" alt="Creative Commons by-nc-sa logo" />

[Back to top](#top)

</div>